import os
from application.feature_extraction.feature_extractor import FeatureExtractor
from domain.models.file_structure import FileStructure

extractor = FeatureExtractor('../../datasets/training/images/content')


def feature_generation() -> list:
    x_train = list()
    vector = list()
    for image in os.listdir('../../datasets/training/images/content'):  # FileStructure.TESTING_IMAGES_PATH (Michael and Charbel Will Explain)
        print(image)
        path = str('../../datasets/training/images/content'+'\\{}'.format(image))

        print(path)

        vector.append(extractor.get_total_pixels(path))
        vector.append(extractor.get_total_black_pixels(path))
        vector.append(extractor.get_total_white_pixels(path))
        vector.append(extractor.get_total_left_pixels(path))
        vector.append(extractor.get_total_right_pixels(path))
        vector.append(extractor.get_total_up_pixels(path))
        vector.append(extractor.get_total_down_pixels(path))
        vector.append(extractor.get_sub_pixels1(path))
        vector.append(extractor.get_sub_pixels2(path))
        vector.append(extractor.get_sub_pixels3(path))
        vector.append(extractor.get_sub_pixels4(path))
        vector.append(extractor.get_sub_pixels5(path))
        vector.append(extractor.get_sub_pixels6(path))
        vector.append(extractor.get_sub_pixels7(path))
        vector.append(extractor.get_sub_pixels8(path))
        vector.append(extractor.get_sub_pixels9(path))
        vector.append(extractor.get_sub_pixels10(path))
        vector.append(extractor.get_sub_pixels11(path))
        vector.append(extractor.get_sub_pixels12(path))
        vector.append(extractor.get_sub_pixels13(path))
        vector.append(extractor.get_sub_pixels14(path))
        vector.append(extractor.get_sub_pixels15(path))
        vector.append(extractor.get_sub_pixels16(path))
        vector.append(extractor.get_sub_pixels17(path))
        vector.append(extractor.get_sub_pixels18(path))
        vector.append(extractor.get_sub_pixels19(path))
        vector.append(extractor.get_sub_pixels20(path))
        vector.append(extractor.get_sub_pixels21(path))
        vector.append(extractor.get_sub_pixels22(path))
        vector.append(extractor.get_sub_pixels23(path))
        vector.append(extractor.get_sub_pixels24(path))
        vector.append(extractor.get_sub_pixels25(path))
        vector.append(extractor.get_sub_pixels26(path))
        vector.append(extractor.get_sub_pixels27(path))
        vector.append(extractor.get_sub_pixels28(path))
        vector.append(extractor.get_sub_pixels29(path))
        vector.append(extractor.get_sub_pixels30(path))
        vector.append(extractor.get_sub_pixels31(path))
        vector.append(extractor.get_sub_pixels32(path))
        vector.append(extractor.get_sub_pixels33(path))
        vector.append(extractor.get_sub_pixels34(path))
        vector.append(extractor.get_sub_pixels35(path))
        vector.append(extractor.get_sub_pixels36(path))
        vector.append(extractor.get_sub_pixels37(path))
        vector.append(extractor.get_sub_pixels38(path))
        vector.append(extractor.get_sub_pixels39(path))
        vector.append(extractor.get_sub_pixels40(path))
        vector.append(extractor.get_sub_pixels41(path))
        vector.append(extractor.get_sub_pixels42(path))
        vector.append(extractor.get_sub_pixels43(path))
        vector.append(extractor.get_sub_pixels44(path))
        vector.append(extractor.get_sub_pixels45(path))
        vector.append(extractor.get_sub_pixels46(path))
        vector.append(extractor.get_sub_pixels47(path))
        vector.append(extractor.get_sub_pixels48(path))
        vector.append(extractor.get_sub_pixels49(path))
        x_train.append(vector)
        vector = list()
    return x_train


def feature_generation_test() -> list:
    x_test = list()
    vector = list()
    for image in os.listdir(
            str('../../datasets/testing/samples')):  # FileStructure.TESTING_IMAGES_PATH (Michael and Charbel Will Explain)
        path = str('../../datasets/testing/samples'+'\\{}'.format(image))
        vector.append(extractor.get_total_pixels(path))
        vector.append(extractor.get_total_black_pixels(path))
        vector.append(extractor.get_total_white_pixels(path))
        vector.append(extractor.get_total_left_pixels(path))
        vector.append(extractor.get_total_right_pixels(path))
        vector.append(extractor.get_total_up_pixels(path))
        vector.append(extractor.get_total_down_pixels(path))
        vector.append(extractor.get_sub_pixels1(path))
        vector.append(extractor.get_sub_pixels2(path))
        vector.append(extractor.get_sub_pixels3(path))
        vector.append(extractor.get_sub_pixels4(path))
        vector.append(extractor.get_sub_pixels5(path))
        vector.append(extractor.get_sub_pixels6(path))
        vector.append(extractor.get_sub_pixels7(path))
        vector.append(extractor.get_sub_pixels8(path))
        vector.append(extractor.get_sub_pixels9(path))
        vector.append(extractor.get_sub_pixels10(path))
        vector.append(extractor.get_sub_pixels11(path))
        vector.append(extractor.get_sub_pixels12(path))
        vector.append(extractor.get_sub_pixels13(path))
        vector.append(extractor.get_sub_pixels14(path))
        vector.append(extractor.get_sub_pixels15(path))
        vector.append(extractor.get_sub_pixels16(path))
        vector.append(extractor.get_sub_pixels17(path))
        vector.append(extractor.get_sub_pixels18(path))
        vector.append(extractor.get_sub_pixels19(path))
        vector.append(extractor.get_sub_pixels20(path))
        vector.append(extractor.get_sub_pixels21(path))
        vector.append(extractor.get_sub_pixels22(path))
        vector.append(extractor.get_sub_pixels23(path))
        vector.append(extractor.get_sub_pixels24(path))
        vector.append(extractor.get_sub_pixels25(path))
        vector.append(extractor.get_sub_pixels26(path))
        vector.append(extractor.get_sub_pixels27(path))
        vector.append(extractor.get_sub_pixels28(path))
        vector.append(extractor.get_sub_pixels29(path))
        vector.append(extractor.get_sub_pixels30(path))
        vector.append(extractor.get_sub_pixels31(path))
        vector.append(extractor.get_sub_pixels32(path))
        vector.append(extractor.get_sub_pixels33(path))
        vector.append(extractor.get_sub_pixels34(path))
        vector.append(extractor.get_sub_pixels35(path))
        vector.append(extractor.get_sub_pixels36(path))
        vector.append(extractor.get_sub_pixels37(path))
        vector.append(extractor.get_sub_pixels38(path))
        vector.append(extractor.get_sub_pixels39(path))
        vector.append(extractor.get_sub_pixels40(path))
        vector.append(extractor.get_sub_pixels41(path))
        vector.append(extractor.get_sub_pixels42(path))
        vector.append(extractor.get_sub_pixels43(path))
        vector.append(extractor.get_sub_pixels44(path))
        vector.append(extractor.get_sub_pixels45(path))
        vector.append(extractor.get_sub_pixels46(path))
        vector.append(extractor.get_sub_pixels47(path))
        vector.append(extractor.get_sub_pixels48(path))
        vector.append(extractor.get_sub_pixels49(path))
        x_test.append(vector)
        vector = list()
    return x_test
